### ISSUE TITLE
Feature required

### ISSUE THREAD

**Issue by MrJai** [nitishmakhija/EasyTipView#5]
Hi @nitishmakhija 

I am working on an app where I need to show coach marks, and your utility is really simple and easy to use, but still scalable enough to serve the purpose, so I would like to thank you for that.

The only thing missing is the ability to add a button to it, because user will never realise how to dismiss it, either by tapping it or tapping anywhere else, so there should be a button with customisable text, like Ok or Next or something.

Looking forward to your response.

Regards,

**Comment by nitishmakhija** [comment]
@MrJai sorry for replying late I am just maintaining this repo, enhancements as pull requests are welcomed
