### ISSUE TITLE
Safe Area is not respected with the TipView

### ISSUE THREAD

**Issue by eschos24** [nitishmakhija/EasyTipView#6]
If a TipView is presented close to the edge of the screen, it will go beyond the bounds of the safe area, so it can be cut off by the notch. This is particularly apparent in landscape mode. 

Thank you so much for supporting an Objective-C version of this!! 👍

**Comment by nitishmakhija** [comment]
#1076e95

**Comment by nitishmakhija** [comment]
ac30c0318629a4c24b51d01d34f656edae84bca2 
Added support for safeArea
