### ISSUE TITLE
Inconsistent corner radius

### ISSUE THREAD

**Issue by bohrium272** [nitishmakhija/EasyTipView#9]
Tip in `right` arrow position has inconsistent corner radius
![simulator screen shot - iphone 8 - 2018-09-07 at 15 01 34](https://user-images.githubusercontent.com/9051659/45212187-dfe3bd80-b2b1-11e8-8962-9ed3f6eb175f.png)

**Comment by nitishmakhija** [comment]
Fixed please update to version `1.2`,

Thanks for using this repo ❤️.
